# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 417)
        icon = QtGui.QIcon.fromTheme("minecraft")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabs.setObjectName("mainTabs")
        self.tab_instances = QtWidgets.QWidget()
        self.tab_instances.setObjectName("tab_instances")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_instances)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instance_scroll = QtWidgets.QScrollArea(self.tab_instances)
        self.instance_scroll.setWidgetResizable(True)
        self.instance_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instance_scroll.setObjectName("instance_scroll")
        self.fjhgdsf = QtWidgets.QWidget()
        self.fjhgdsf.setGeometry(QtCore.QRect(0, 0, 475, 292))
        self.fjhgdsf.setObjectName("fjhgdsf")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fjhgdsf)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.instance_box = QtWidgets.QVBoxLayout()
        self.instance_box.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.instance_box.setObjectName("instance_box")
        self.verticalLayout_4.addLayout(self.instance_box)
        self.instance_scroll.setWidget(self.fjhgdsf)
        self.verticalLayout.addWidget(self.instance_scroll)
        self.mainTabs.addTab(self.tab_instances, "")
        self.tab_browse = QtWidgets.QWidget()
        self.tab_browse.setObjectName("tab_browse")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_browse)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pack_scroll = QtWidgets.QScrollArea(self.tab_browse)
        self.pack_scroll.setWidgetResizable(True)
        self.pack_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pack_scroll.setObjectName("pack_scroll")
        self.fjhgdsf_2 = QtWidgets.QWidget()
        self.fjhgdsf_2.setGeometry(QtCore.QRect(0, 0, 475, 292))
        self.fjhgdsf_2.setObjectName("fjhgdsf_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fjhgdsf_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pack_box = QtWidgets.QVBoxLayout()
        self.pack_box.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.pack_box.setObjectName("pack_box")
        self.verticalLayout_9.addLayout(self.pack_box)
        self.pack_scroll.setWidget(self.fjhgdsf_2)
        self.verticalLayout_10.addWidget(self.pack_scroll)
        self.mainTabs.addTab(self.tab_browse, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mmc_group = QtWidgets.QGroupBox(self.tab_settings)
        self.mmc_group.setObjectName("mmc_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mmc_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mmc_folder = QtWidgets.QLineEdit(self.mmc_group)
        self.mmc_folder.setToolTip("")
        self.mmc_folder.setReadOnly(True)
        self.mmc_folder.setObjectName("mmc_folder")
        self.horizontalLayout.addWidget(self.mmc_folder)
        self.mmc_edit = QtWidgets.QToolButton(self.mmc_group)
        self.mmc_edit.setToolTip("")
        icon = QtGui.QIcon.fromTheme("edit")
        self.mmc_edit.setIcon(icon)
        self.mmc_edit.setObjectName("mmc_edit")
        self.horizontalLayout.addWidget(self.mmc_edit)
        self.verticalLayout_3.addWidget(self.mmc_group, 0, QtCore.Qt.AlignTop)
        self.mainTabs.addTab(self.tab_settings, "")
        self.verticalLayout_2.addWidget(self.mainTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_instances), _translate("MainWindow", "Instances"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_browse), _translate("MainWindow", "Browse Packs"))
        self.mmc_group.setTitle(_translate("MainWindow", "MultiMC Folder"))
        self.mmc_folder.setPlaceholderText(_translate("MainWindow", "Folder"))
        self.mmc_edit.setText(_translate("MainWindow", "..."))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))

