# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        icon = QtGui.QIcon.fromTheme("minecraft")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabs.setObjectName("mainTabs")
        self.tab_instances = QtWidgets.QWidget()
        self.tab_instances.setObjectName("tab_instances")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_instances)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instance_scroll = QtWidgets.QScrollArea(self.tab_instances)
        self.instance_scroll.setWidgetResizable(True)
        self.instance_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instance_scroll.setObjectName("instance_scroll")
        self.fjhgdsf = QtWidgets.QWidget()
        self.fjhgdsf.setGeometry(QtCore.QRect(0, 0, 458, 301))
        self.fjhgdsf.setObjectName("fjhgdsf")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fjhgdsf)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.instance_box = QtWidgets.QVBoxLayout()
        self.instance_box.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.instance_box.setObjectName("instance_box")
        self.verticalLayout_4.addLayout(self.instance_box)
        self.instance_scroll.setWidget(self.fjhgdsf)
        self.verticalLayout.addWidget(self.instance_scroll)
        self.mainTabs.addTab(self.tab_instances, "")
        self.tab_browse = QtWidgets.QWidget()
        self.tab_browse.setObjectName("tab_browse")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_browse)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame = QtWidgets.QFrame(self.tab_browse)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pack_search = QtWidgets.QLineEdit(self.frame)
        self.pack_search.setObjectName("pack_search")
        self.horizontalLayout_4.addWidget(self.pack_search)
        self.pack_search_button = QtWidgets.QToolButton(self.frame)
        icon = QtGui.QIcon.fromTheme("search")
        self.pack_search_button.setIcon(icon)
        self.pack_search_button.setObjectName("pack_search_button")
        self.horizontalLayout_4.addWidget(self.pack_search_button)
        self.verticalLayout_10.addWidget(self.frame)
        self.pack_scroll = QtWidgets.QScrollArea(self.tab_browse)
        self.pack_scroll.setWidgetResizable(True)
        self.pack_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pack_scroll.setObjectName("pack_scroll")
        self.fjhgdsf_2 = QtWidgets.QWidget()
        self.fjhgdsf_2.setGeometry(QtCore.QRect(0, 0, 458, 248))
        self.fjhgdsf_2.setObjectName("fjhgdsf_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fjhgdsf_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pack_box = QtWidgets.QVBoxLayout()
        self.pack_box.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.pack_box.setObjectName("pack_box")
        self.loading_label = QtWidgets.QLabel(self.fjhgdsf_2)
        self.loading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loading_label.setObjectName("loading_label")
        self.pack_box.addWidget(self.loading_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pack_box.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.pack_box)
        self.pack_scroll.setWidget(self.fjhgdsf_2)
        self.verticalLayout_10.addWidget(self.pack_scroll)
        self.mainTabs.addTab(self.tab_browse, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mmc_group = QtWidgets.QGroupBox(self.tab_settings)
        self.mmc_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mmc_group.setObjectName("mmc_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mmc_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mmc_folder = QtWidgets.QLineEdit(self.mmc_group)
        self.mmc_folder.setToolTip("")
        self.mmc_folder.setReadOnly(True)
        self.mmc_folder.setObjectName("mmc_folder")
        self.horizontalLayout.addWidget(self.mmc_folder)
        self.mmc_edit = QtWidgets.QToolButton(self.mmc_group)
        self.mmc_edit.setToolTip("")
        icon = QtGui.QIcon.fromTheme("edit")
        self.mmc_edit.setIcon(icon)
        self.mmc_edit.setObjectName("mmc_edit")
        self.horizontalLayout.addWidget(self.mmc_edit)
        self.verticalLayout_3.addWidget(self.mmc_group, 0, QtCore.Qt.AlignTop)
        self.analytics_group = QtWidgets.QGroupBox(self.tab_settings)
        self.analytics_group.setObjectName("analytics_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.analytics_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.analytics_label = QtWidgets.QLabel(self.analytics_group)
        self.analytics_label.setObjectName("analytics_label")
        self.horizontalLayout_2.addWidget(self.analytics_label)
        self.analytics_check = QtWidgets.QCheckBox(self.analytics_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analytics_check.sizePolicy().hasHeightForWidth())
        self.analytics_check.setSizePolicy(sizePolicy)
        self.analytics_check.setMaximumSize(QtCore.QSize(16, 16777215))
        self.analytics_check.setText("")
        self.analytics_check.setObjectName("analytics_check")
        self.horizontalLayout_2.addWidget(self.analytics_check)
        self.verticalLayout_3.addWidget(self.analytics_group)
        self.groupBox = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.update_check = QtWidgets.QCheckBox(self.groupBox)
        self.update_check.setMaximumSize(QtCore.QSize(16, 16777215))
        self.update_check.setText("")
        self.update_check.setObjectName("update_check")
        self.horizontalLayout_3.addWidget(self.update_check)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.file_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.file_check.setMaximumSize(QtCore.QSize(16, 16777215))
        self.file_check.setText("")
        self.file_check.setObjectName("file_check")
        self.horizontalLayout_5.addWidget(self.file_check)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.mainTabs.addTab(self.tab_settings, "")
        self.verticalLayout_2.addWidget(self.mainTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_instances), _translate("MainWindow", "Instances"))
        self.pack_search_button.setText(_translate("MainWindow", "..."))
        self.loading_label.setText(_translate("MainWindow", "Loading..."))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_browse), _translate("MainWindow", "Browse Packs"))
        self.mmc_group.setTitle(_translate("MainWindow", "MultiMC Folder"))
        self.mmc_folder.setPlaceholderText(_translate("MainWindow", "Folder"))
        self.mmc_edit.setText(_translate("MainWindow", "..."))
        self.analytics_group.setTitle(_translate("MainWindow", "Analytics"))
        self.analytics_label.setText(_translate("MainWindow", "Send basic analytics:"))
        self.groupBox.setTitle(_translate("MainWindow", "Update Checker"))
        self.label.setText(_translate("MainWindow", "Check for updates when opening OpenMineMods:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "File Picker"))
        self.label_2.setText(_translate("MainWindow", "Choose file before installing:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))

